server:
  port: 3001

spring:
  output.ansi.enabled: always

  kafka:
    producer:
      bootstrap-servers:
        - localhost:29092
        - localhost:39092


    consumer:
      auto-offset-reset: earliest
      group-id: group_id
      bootstrap-servers:
        - localhost:29092
        - localhost:39092
