server:
  port: 3001


  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest

    producer:
      bootstrap-servers: localhost:9092


logging:
  level:
    ROOT: INFO